# PyTorch
> PyTorch使用

In [6]:
import numpy as np
from torch import tensor

## 基本方法

`torch.zeros`创建一个用零填充的张量

In [5]:
import torch

x = torch.zeros(2,3)

print(x)
print(x.shape)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.Size([2, 3])


## Tensor

tensor shape修改

In [10]:
nums = [i for i in range(12)]
nums = tensor(np.asarray(nums))
nums.shape

torch.Size([12])

In [11]:
nums

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## 维度操作

You can index with the special value [None] or use `unsqueeze()` to convert a 1-dimensional array into a 2-dimensional array (although one of those dimensions has value 1).

In [14]:
nums[:,None][:3], nums.unsqueeze(1)[:3]

(tensor([[0],
         [1],
         [2]]),
 tensor([[0],
         [1],
         [2]]))

### torch.tensor.view 方法
[参见： 文档](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html)

修改维度形状， 返回一个具有相同数量，但是不同shape的新的tensor

In [8]:
x = torch.randn(4, 4)
print('before shape:',x.shape)
y = x.view(16)
print('after shape:',y.shape)
z = x.view(-1, 8) # -1表示自动推断维度大小
print('after2 shape:', z.shape)

before shape: torch.Size([4, 4])
after shape: torch.Size([16])
after2 shape: torch.Size([2, 8])


In [32]:
nums_2d = nums.view(4, 3) 
nums_2d

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

可以省略一个维度的数量，设置为-1

In [28]:
nums.view(4,-1)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [29]:
nums.view(-1, 2,3)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])

In [34]:
nums_2d.shape

torch.Size([4, 3])

### `repeat`复制数据

PyTorch的repeat方法主要用于副本复制张量, repeat方法会沿着指定维度重复整个输入张量,生成新的输出张量。

In [55]:
nums = [i for i in range(12)]
nums = tensor(nums).view(-1, 2)
nums

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])

In [58]:
nums_rp = nums.repeat(1, 3)
nums_rp

tensor([[ 0,  1,  0,  1,  0,  1],
        [ 2,  3,  2,  3,  2,  3],
        [ 4,  5,  4,  5,  4,  5],
        [ 6,  7,  6,  7,  6,  7],
        [ 8,  9,  8,  9,  8,  9],
        [10, 11, 10, 11, 10, 11]])

In [61]:
nums_rp.view(-1, 2)[:3]

tensor([[0, 1],
        [0, 1],
        [0, 1]])

## `expand_as` 扩展维度

In [2]:
c = tensor([10., 20,30]); c

tensor([10., 20., 30.])

In [3]:
m = tensor([[1., 2, 3], [4,5,6], [7,8,9]]); m

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [4]:
c.expand_as(m)

tensor([[10., 20., 30.],
        [10., 20., 30.],
        [10., 20., 30.]])