# PyTorch
> PyTorch使用

In [8]:
import numpy as np
from torch import tensor

# Tensor

tensor shape修改

In [22]:
nums = [i for i in range(12)]

In [23]:
nums = tensor(np.asarray(nums))
nums.shape

torch.Size([12])

## 提升维度

如果只是想升维，不需要修改数量，可以使用如下方法

In [31]:
nums[:,None][:3]

tensor([[0],
        [1],
        [2]])

如果需要限定维度，需要使用view方法

In [32]:
nums_2d = nums.view(4, 3) 
nums_2d

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

可以省略一个维度的数量，设置为-1

In [28]:
nums.view(4,-1)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [29]:
nums.view(-1, 2,3)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])

In [34]:
nums_2d.shape

torch.Size([4, 3])

## 复制数据

PyTorch的repeat方法主要用于副本复制张量, repeat方法会沿着指定维度重复整个输入张量,生成新的输出张量。

In [55]:
nums = [i for i in range(12)]
nums = tensor(nums).view(-1, 2)
nums

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])

In [58]:
nums_rp = nums.repeat(1, 3)
nums_rp

tensor([[ 0,  1,  0,  1,  0,  1],
        [ 2,  3,  2,  3,  2,  3],
        [ 4,  5,  4,  5,  4,  5],
        [ 6,  7,  6,  7,  6,  7],
        [ 8,  9,  8,  9,  8,  9],
        [10, 11, 10, 11, 10, 11]])

In [61]:
nums_rp.view(-1, 2)[:3]

tensor([[0, 1],
        [0, 1],
        [0, 1]])