# FastAI
> FastAI致力于简化深度学习任务的流程，使得从数据预处理到模型训练和部署都变得更加容易和快速。

## 基本用法

[官方文档](https://docs.fast.ai/quick_start.html)

FastAI 是一个深度学习库，它为从业者提供高级组件，这些组件可以在标准深度学习领域快速轻松地使用

Fastai 提供了对四种数据的深度学习，分别是图像、文本、协同过滤、表格，导入方式分别是
```
from fastai.vision.all import *
from fastai.text.all import *
from fastai.collab import *
from fastai.tabular.all import *
```

In [13]:
from fastai.tabular.all import *

In [14]:
path = untar_data(URLs.ADULT_SAMPLE)
path.ls()

(#3) [Path('/Users/hawkins/.fastai/data/adult_sample/adult.csv'),Path('/Users/hawkins/.fastai/data/adult_sample/export.pkl'),Path('/Users/hawkins/.fastai/data/adult_sample/models')]

In [16]:
df = pd.read_csv(path/'adult.csv')
df.head()

age          workclass  fnlwgt     education  education-num  \
0   49            Private  101320    Assoc-acdm           12.0   
1   44            Private  236746       Masters           14.0   
2   38            Private   96185       HS-grad            NaN   
3   38       Self-emp-inc  112847   Prof-school           15.0   
4   42   Self-emp-not-inc   82297       7th-8th            NaN   

        marital-status        occupation    relationship                 race  \
0   Married-civ-spouse               NaN            Wife                White   
1             Divorced   Exec-managerial   Not-in-family                White   
2             Divorced               NaN       Unmarried                Black   
3   Married-civ-spouse    Prof-specialty         Husband   Asian-Pac-Islander   
4   Married-civ-spouse     Other-service            Wife                Black   

       sex  capital-gain  capital-loss  hours-per-week  native-country salary  
0   Female             0          1902              40   United-States  >=50k  
1     Male         10520             0              45   United-States  >=50k  
2   Female             0             0              32   United-States   <50k  
3     Male             0             0              40   United-States  >=50k  
4   Female             0             0              50   United-States   <50k

In [17]:
dls = TabularDataLoaders.from_csv(path/'adult.csv', path=path, y_names="salary",
    cat_names = ['workclass', 'education', 'marital-status', 'occupation',
                 'relationship', 'race'],
    cont_names = ['age', 'fnlwgt', 'education-num'],
    procs = [Categorify, FillMissing, Normalize])

/Users/hawkins/miniconda3/envs/ai/lib/python3.10/site-packages/fastai/tabular/core.py:312: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  to[n].fillna(self.na_dict[n], inplace=True)


In [11]:
dls.show_batch()

In [12]:
learn = tabular_learner(dls, metrics=accuracy)
learn.fit_one_cycle(2)

In [127]:
import torch
import torch.nn.functional as F

# 模型的输出
output = torch.tensor([1.2, 0.5, -0.1, 2.3, 1.8])

# 计算对数概率
log_probs = F.log_softmax(output, dim=0)

# 打印每个标签的概率
for i, log_prob in enumerate(log_probs):
    print(f"Label {i}: {torch.exp(log_prob)}")

Label 0: 0.1516208052635193
Label 1: 0.0752926617860794
Label 2: 0.041321493685245514
Label 3: 0.4554940164089203
Label 4: 0.27627110481262207


In [129]:
log_probs.sum()

tensor(-9.7319)

In [38]:
import torch

x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

# 重新排列维度
y = x.permute(1, 0)
print(y)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [14]:
hidden_size = 128
lstm = nn.LSTM(12, 128, batch_first=True, num_layers=1) # 输入
output, (hn, cn) = lstm(input)

In [12]:
output.shape, hn.shape, cn.shape

(torch.Size([64, 128]), torch.Size([1, 128]), torch.Size([1, 128]))

In [42]:
lstm = nn.LSTM(3, 3)
lstm.all_weights

[[Parameter containing:
  tensor([[-0.2712,  0.0327,  0.4179],
          [-0.4061,  0.2711,  0.3709],
          [ 0.5648, -0.4041,  0.1398],
          [-0.4269,  0.4929, -0.2240],
          [ 0.3478,  0.0172, -0.0450],
          [-0.0184,  0.0981,  0.2722],
          [ 0.0926,  0.1761, -0.5193],
          [ 0.4206,  0.5034,  0.4772],
          [ 0.4268, -0.4166, -0.2140],
          [ 0.5091, -0.4397,  0.5238],
          [-0.4541, -0.4067,  0.2823],
          [-0.4148, -0.1323,  0.4200]], requires_grad=True),
  Parameter containing:
  tensor([[ 0.4573,  0.5460, -0.1172],
          [-0.4488,  0.5685, -0.1230],
          [-0.2375,  0.1407, -0.4038],
          [ 0.3795,  0.3618, -0.4581],
          [-0.4742, -0.0506,  0.2425],
          [-0.0167, -0.2928,  0.0132],
          [-0.5427, -0.4080, -0.3843],
          [ 0.4755,  0.5089, -0.1961],
          [ 0.0259,  0.2575,  0.0692],
          [-0.2891,  0.3330,  0.3549],
          [-0.0335, -0.0711,  0.5247],
          [ 0.5047, -0.3273,  0.5

In [114]:
inputs = [torch.randn(1,3) for _ in range(5)]
inputs = torch.cat(inputs).view(len(inputs), 1, -1)
inputs.shape

torch.Size([5, 1, 3])

In [45]:
# 初始化隐藏状态
hidden = (torch.randn(1, 1, 3),
          torch.randn(1, 1, 3))

In [58]:
inputs[1], inputs[1].shape

torch.Size([1, 3])

In [59]:
inputs[1].view(1, 1, -1), inputs[1].view(1, 1, -1).shape

(tensor([[[ 0.6706, -0.4929,  1.5050]]]), torch.Size([1, 1, 3]))

In [46]:
for i in inputs:
     out, hidden = lstm(i.view(1, 1, -1), hidden)

In [47]:
out

tensor([[[ 0.1575,  0.0259, -0.0575]]], grad_fn=<MkldnnRnnLayerBackward0>)

## 准备数据

In [124]:
feature_size = 3
total = 15
batch_size = 5

inputs = [torch.randn(1,feature_size) for _ in range(total)]


def get_batch_iter():
    for i in range(0, total, batch_size):
        yield torch.cat(inputs[i:min(i+batch_size, total)])

batch_iter = get_batch_iter()
x = next(batch_iter)

In [125]:
x.shape, x.size(0)

(torch.Size([5, 3]), 5)

## 构建模型
class torch.nn.LSTM(*args, **kwargs)

参数列表

- input_size：x的特征维度
- hidden_size：隐藏层的特征维度
- num_layers：lstm隐层的层数，默认为1
- bias：False则bih=0和bhh=0. 默认为True
- batch_first：True则输入输出的数据格式为 (batch, seq, feature)
- dropout：除最后一层，每一层的输出都进行dropout，默认为: 0
- bidirectional：True则为双向lstm默认为False
- 输入：input, (h0, c0)
- 输出：output, (hn,cn)

In [126]:
input_size = feature_size
num_layers = 1
hidden_size = 3

lstm = nn.LSTM(input_size, hidden_size, batch_first=True, num_layers=num_layers) # 输入

## 模型训练

In [118]:
# 输入：input, (h0, c0)
# 输入数据格式：
# input(batch, seq_len, input_size)
# h0(num_layers * num_directions, batch, hidden_size)
# c0(num_layers * num_directions, batch, hidden_size)
# num_directions 代表lstm的方向数，其实就是是否为双向lstm。如果你用的网络是双向（bidirectional==True）则num_directions’为2，如果不是，则为1

h0 = torch.zeros(num_layers, x.size(0), hidden_size)
c0 = torch.zeros(num_layers, x.size(0), hidden_size)
hidden = (h0, c0)  


# LSTM 返回的第一个值表示所有时刻的隐状态值, 第二个值表示最近的隐状态值 (因此下面的 "out"的最后一个值和 "hidden" 的值是一样的).
# 之所以这样设计, 是为了通过 "out" 的值来获取所有的隐状态值, 而用 "hidden" 的值来
# 进行序列的反向传播运算, 具体方式就是将它作为参数传入后面的 LSTM 网络.
out, (hn, cn) = lstm(x, hidden)

> **注意：input 的batch 必须和hidden的batch，也就是第二个参数相同！** 

In [119]:
# 输出数据格式：
# output(batch, seq_len,  hidden_size * num_directions)
# hn(num_layers * num_directions, batch, hidden_size)
# cn(num_layers * num_directions, batch, hidden_size)

out.shape, hn.shape, cn.shape

(torch.Size([5, 1, 3]), torch.Size([1, 5, 3]), torch.Size([1, 5, 3]))

In [120]:
out, (hn, cn) 

(tensor([[[-8.5360e-02, -4.1744e-03, -1.4452e-01]],
 
         [[-8.6979e-05, -9.0539e-02,  1.4557e-01]],
 
         [[-8.8682e-02,  9.1704e-02, -1.1052e-01]],
 
         [[-1.2795e-01,  8.7705e-02, -1.8030e-01]],
 
         [[ 2.3082e-01, -1.1413e-01,  8.8840e-02]]],
        grad_fn=<TransposeBackward0>),
 (tensor([[[-8.5360e-02, -4.1744e-03, -1.4452e-01],
           [-8.6979e-05, -9.0539e-02,  1.4557e-01],
           [-8.8682e-02,  9.1704e-02, -1.1052e-01],
           [-1.2795e-01,  8.7705e-02, -1.8030e-01],
           [ 2.3082e-01, -1.1413e-01,  8.8840e-02]]], grad_fn=<StackBackward0>),
  tensor([[[-1.8463e-01, -6.7775e-03, -3.8707e-01],
           [-2.8391e-04, -1.1626e-01,  3.0000e-01],
           [-1.9160e-01,  1.3820e-01, -2.7486e-01],
           [-3.2372e-01,  1.3617e-01, -6.0256e-01],
           [ 3.8518e-01, -2.5076e-01,  1.8670e-01]]], grad_fn=<StackBackward0>)))

In [ ]:
class LSTMModel(Module):
    "Basic model for tabular data."
    def __init__(self, 
        emb_szs:list, # Sequence of (num_embeddings, embedding_dim) for each categorical variable
        n_cont:int, # Number of continuous variables
        out_sz:int, # Number of outputs for final `LinBnDrop` layer
        layers:list, # Sequence of ints used to specify the input and output size of each `LinBnDrop` layer
        ps:float|MutableSequence=None, # Sequence of dropout probabilities for `LinBnDrop`
        embed_p:float=0., # Dropout probability for `Embedding` layer
        y_range=None, # Low and high for `SigmoidRange` activation 
        use_bn:bool=True, # Use `BatchNorm1d` in `LinBnDrop` layers
        bn_final:bool=False, # Use `BatchNorm1d` on final layer
        bn_cont:bool=True, # Use `BatchNorm1d` on continuous variables
        act_cls=nn.ReLU(inplace=True), # Activation type for `LinBnDrop` layers
        n_lstm=1,
        lin_first:bool=True # Linear layer is first or last in `LinBnDrop` layers
    ):
        ps = ifnone(ps, [0]*len(layers))
        if not is_listy(ps): ps = [ps]*len(layers)
        self.bn_cont = nn.BatchNorm1d(n_cont) if bn_cont else None
        self.n_cont = n_cont
        sizes = [n_cont] + layers + [out_sz]
        actns = [act_cls for _ in range(len(sizes)-2)] + [None]
        _layers = [LinBnDrop(sizes[i], sizes[i+1], bn=use_bn and (i!=len(actns)-1 or bn_final), p=p, act=a, lin_first=lin_first)
                       for i,(p,a) in enumerate(zip(ps+[0.],actns))]
        if y_range is not None: _layers.append(SigmoidRange(*y_range))
        self.layers = nn.Sequential(*_layers)
        self.lstm = nn.LSTM(n_cont, 64, batch_first=True, num_layers=1)

    def forward(self, x_cat, x_cont=None):
        x_lstm, _ = self.lstm(x_cont)
        x_lstm = x_lstm[-1, :]
        x_cont = self.bn_cont(x_cont)
        x = torch.cat([x_cont, x_lstm], 1)
        return self.layers(x)

In [ ]:
# splitter = EndSplitter(valid_pct=0.2, valid_last=True)(range_of(train_all))
splitter = RandomSplitter(valid_pct=0.2)(range_of(train_all))

to = TabularPandas(train_all, procs=[FillMissing,Normalize],
                   cont_names = features,
                   y_block = CategoryBlock,
                   y_names='awake',
                   splits=splitter, 
                   device=def_device) # Important: Specify training on GPU 

dls = to.dataloaders(bs=12*60*24, num_workers=4) # Important: use multiple threads.

dls.show_batch()

In [ ]:
def get_event(df):
    lstCV = zip(df.series_id, df.smooth)
    lstPOI = []
    for (c, v), g in groupby(lstCV, lambda cv: (cv[0], cv[1] != 0 and not pd.isnull(cv[1]))):
        llg = sum(1 for item in g)
        print(c,v,llg)
        if v is False:
            lstPOI.extend([0] * llg)
        else:
            lstPOI.extend(['onset'] + (llg - 2) * [0] + ['wakeup'] if llg > 1 else [0])
    return lstPOI

test_p["event"] = get_event(test_p)